function infoBox
     msgbox([{'This program was created on 22.04.2020 by Andreas Bernatzky.'},...
       {'This program shows the parameter sensitivity of a paramPoly3 like it is'}...
       {'specified in the OpenDrive standard: http://opendrive.org/docs/OpenDRIVEFormatSpecRev1.5M.pdf'},...
       {'The default parameters of the shown paramPoly3 are:'},...
       {' aU = 0.0'},...
       {' bU = 1.0'},...
       {' cU = -0.124'},...
       {' dU = 0.00957'},...
       {' cV = 0.186'},...
       {' dV = -0.0112'},...
       {' startHdg = 5.971'},...
       {' startX = 16'},...
       {' startY = -4'},...
       {' length = 7.37'}]);

end

